- hosts: servers
  become: true
  pre_tasks:
      - name: update package cache (debian-based)
        apt: update_cache=yes
        when: ansible_distribution in ['Debian', 'Ubuntu'] 
  roles:
  - role: base
  - role: users
  - role: servers

- hosts: ups_controlled:&servers
  become: true
  roles:
    - role: ups_controlled

- hosts: kvm_hosts:&servers
  become: true
  roles:
    - role: kvm_host

- hosts: workstations:&servers
  become: true
  roles:
    - role: workstations

