- hosts: all
  become: true
  roles:
  - role: base
  - role: users

- hosts: servers
  become: true
  roles:
    - role: servers


- hosts: nagios_monitored
  become: true
  roles:
    - role: nagios_monitored


- hosts: workstations
  become: true
  roles:
    - role: workstations


- hosts: games
  become: true
  roles:
    - role: games


- hosts: gnome
  become: true
  roles:
    - role: gnome


- hosts: mate
  become: true
  roles:
    - role: mate


- hosts: openbox
  become: true
  roles:
    - role: openbox


- hosts: gdm
  become: true
  roles:
    - role: gdm


- hosts: lightdm
  become: true
  roles:
    - role: lightdm


- hosts: ups_controlled
  become: true
  roles:
    - role: ups_controlled


- hosts: raspberry-pi
  become: true
  roles:
    - role: raspberry-pi


- hosts: kvm_hosts
  become: true
  roles:
    - role: kvm_host
