- name: create /vm_store directory
  file: path=/vm_store state=directory owner=root mode=770 recurse=no

- name: create /vm_store/vbox directory
  file: path=/vm_store state=directory owner=jay group=jay mode=770 recurse=no
