- name: install virtualbox packages
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - linux-headers
    - virtualbox
    - virtualbox-guest-iso
