- name: install virtualbox repository (debian)
  copy: src=debian-virtualbox.list dest=/etc/apt/sources.list.d/virtualbox.list owner=root group=root mode=644
  when: ansible_distribution in ['Debian']
  register: apt

- name: install virtualbox repository (ubuntu)
  copy: src=ubuntu-virtualbox.list dest=/etc/apt/sources.list.d/virtualbox.list owner=root group=root mode=644
  when: ansible_distribution in ['Ubuntu']
  register: apt

- name: Add virtualbox repository key (debian-based)
  apt_key: url=https://www.virtualbox.org/download/oracle_vbox_2016.asc state=present

- name: apt-update
  apt: update_cache=yes
  when: apt.changed
  changed_when: False

- name: install virtualbox repository (fedora)
  yum_repository:
  name: virtualbox
  description: VirtualBox repository
  baseurl: http://download.virtualbox.org/virtualbox/rpm/fedora/$releasever/$basearch
  gpgkey: https://www.virtualbox.org/download/oracle_vbox.asc
  gpgcheck: yes
