- name: disable lightdm
  service: name=lightdm enabled=no

- name: enable gdm (arch)
  service: name=gdm enabled=yes
  when: ansible_distribution in ['Archlinux', 'Fedora', 'Manjaro Linux']

- name: enable gdm3 (debian-based)
  service: name=gdm3 enabled=yes
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
