firefox_version: 43.0.2
syncthing_version: 0.12.9
thunderbird_version: 38.5.0
syncthing_url: https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-linux-amd64-v{{syncthing_version}}.tar.gz
syncthing_config: /home/jay/.config/syncthing/config.xml
firefox_url: https://ftp.mozilla.org/pub/firefox/releases/{{firefox_version}}/linux-x86_64/en-US/firefox-{{firefox_version}}.tar.bz2
thunderbird_url: https://ftp.mozilla.org/pub/thunderbird/releases/{{thunderbird_version}}/linux-x86_64/en-US/thunderbird-{{thunderbird_version}}.tar.bz2
app_dir: /home/jay/bin
