- name: create mame directory (debian-based)
  file: path=/etc/mame state=directory owner=root group=root mode=755
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
   
- name: copy mame.ini (debian-based)
  copy: src=mame.ini dest=/etc/mame/mame.ini owner=root group=users mode=644
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: create mame directory (arch)
  file: path=/home/jay/.mame state=directory owner=jay group=jay mode=700
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
   
- name: copy mame.ini (arch)
  copy: src=mame.ini dest=/home/jay/.mame/mame.ini owner=jay group=jay mode=600
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']

