- name: install games on archlinux hosts
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro']
  with_items:
    - chromium-bsu
    - frozen-bubble
    - lib32-gcc-libs
    - lib32-libpulse
    - mednafen
    - neverball
    - sdlmame
    - supertux
    - supertuxkart
    - wesnoth
