- name: install games on ubuntu hosts
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Ubuntu']
  with_items:
    - chromium-bsu
    - frozen-bubble
    - libasound2-data
    - libasound2-plugins:i386
    - libc6:i386
    - mame
    - mednafen
    - neverball
    - supertux
    - supertuxkart
    - wesnoth
