- name: install mate (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  with_items:
    - atril
    - caja
    - eom
    - mate-applets
    - mate-backgrounds
    - mate-control-center
    - mate-desktop
    - mate-icon-theme
    - mate-media
    - mate-menus
    - mate-notification-daemon
    - mate-panel
    - mate-polkit
    - mate-power-manager
    - mate-screensaver
    - mate-session-manager
    - mate-settings-daemon
    - mate-system-monitor
    - mate-terminal
    - mate-themes
    - mozo
    - pluma

- name: install mate-media-pulse (debian)
  apt: name=mate-media-pulse
  when: ansible_distribution == 'debian'

- name: install mate-media-pulse (debian)
  apt: name=mate-media-settings-daemon-pulse
  when: ansible_distribution == 'debian'
