- name: install mate
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - atril
    - caja
    - eom
    - mate-applets
    - mate-backgrounds
    - mate-control-center
    - mate-desktop
    - mate-icon-theme
    - mate-media
    - mate-menus
    - mate-notification-daemon
    - mate-power-manager
    - mate-screensaver
    - mate-screensaver-hacks
    - mate-session-manager
    - mate-system-monitor
    - mate-terminal
    - mate-themes
    - mozo
    - pluma
    - ttf-liberation
