- name: install mate
  dnf: name={{item}} state=latest
  when: ansible_distribution == 'Fedora'
  with_items:
    - atril
    - caja
    - dconf
    - dconf-editor
    - eom
    - mate-applets
    - mate-backgrounds
    - mate-control-center
    - mate-desktop
    - mate-icon-theme
    - mate-media
    - mate-menus
    - mate-notification-daemon
    - mate-screensaver
    - mate-system-monitor
    - mate-terminal
    - mate-themes
    - mozo
    - pluma
