- name: install workstation packages (arch)
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro']
  with_items:
    - asunder
    - banshee
    - brasero
    - cmus
    - conky
    - cryptsetup
    - dialog
    - dmenu
    - easytag
    - exfat-utils
    - filezilla
    - freerdp
    - galculator
    - geany
    - geany-plugins
    - gimp
    - gnome-keyring
    - gparted
    - gtk-engine-aurora
    - gtk-engine-murrine
    - gtk-recordmydesktop
    - guake
    - hunspell-en
    - hyphen-en
    - keepassx
    - libreoffice-still
    - mpv
    - network-manager-applet
    - networkmanager
    - networkmanager-openvpn
    - networkmanager-pptp
    - networkmanager-vpnc
    - pavucontrol
    - perl
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode # To do: Unable to install the proper package, rxvt-unicode-pixbuf, via yaourt
    - shutter
    - smbclient
    - terminator
    - terminus-font
    - transmission-gtk
    - vlc
    - vorbis-tools
    - wireless_tools
    - wpa_actiond
    - wpa_supplicant
    - xorg-xbacklight
    - xsel


- name: install workstation packages (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  with_items:
    - aptitude
    - asunder
    - banshee
    - brasero
    - cmus
    - conky
    - cryptsetup
    - easytag
    - exfat-utils
    - filezilla
    - firmware-iwlwifi
    - freerdp-x11
    - galculator
    - geany
    - geany-plugins
    - gimp
    - gnome-keyring
    - gparted
    - gtk-recordmydesktop
    - gtk2-engines-aurora
    - gtk2-engines-murrine
    - guake
    - hunspell-en-us
    - hyphen-en-us
    - keepassx
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-writer
    - mpv
    - network-manager
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-vpnc
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - smbclient
    - suckless-tools
    - synaptic
    - terminator
    - transmission-gtk
    - vlc
    - vorbis-tools
    - xbacklight
    - xfonts-terminus
    - xsel


- name: install workstation packages (fedora)
  dnf: name={{item}} state=installed
  when: ansible_distribution == 'Fedora'
  with_items:
    - asunder
    - banshee
    - brasero
    #- cmus # Currently not available in Fedora, check this later
    - conky
    - dmenu
    - easytag
    - exfat-utils
    - filezilla
    - freerdp
    - galculator
    - geany
    - gimp
    - gnome-keyring
    - gparted
    - gstreamer-plugins-bad
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer1-plugins-ugly # To do: Which gstreamer packages are actually necessary?
    - gtk2-engines
    - gtk-recordmydesktop
    - guake
    - keepassx
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-writer
    #- mpv # Package not found
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - terminator
    - terminus-fonts
    - transmission-gtk
    - vlc
    - vorbis-tools
    - xbacklight
    - xsel


## Set up directories
- name: create ~/bin
  file: path=/home/jay/bin state=directory owner=jay group=users mode=700

- name: create ~/desktop
  file: path=/home/jay/desktop state=directory owner=jay group=users mode=700

- name: create ~/documents
  file: path=/home/jay/documents state=directory owner=jay group=users mode=700

- name: create ~/downloads
  file: path=/home/jay/downloads state=directory owner=jay group=users mode=700

- name: create ~/games
  file: path=/home/jay/games state=directory owner=jay group=users mode=700

- name: create ~/music
  file: path=/home/jay/music state=directory owner=jay group=users mode=700

- name: create ~/pictures
  file: path=/home/jay/pictures state=directory owner=jay group=users mode=700

- name: create ~/projects
  file: path=/home/jay/projects state=directory owner=jay group=users mode=700

- name: create ~/templates
  file: path=/home/jay/templates state=directory owner=jay group=users mode=700

- name: create ~/videos
  file: path=/home/jay/videos state=directory owner=jay group=users mode=700

- name: create /mnt/pluto
  file: path=/mnt/pluto state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/archive
  file: path=/mnt/pluto/archive state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/backup
  file: path=/mnt/pluto/backup state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/downloads
  file: path=/mnt/pluto/downloads state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/private
  file: path=/mnt/pluto/private state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/public
  file: path=/mnt/pluto/public state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/videos
  file: path=/mnt/pluto/videos state=directory owner=jay group=users mode=700

- name: create /share
  file: path=/share state=directory owner=jay group=users mode=700

- name: create /share/android
  file: path=/share/android state=directory owner=jay group=users mode=700

- name: create /share/android/camera
  file: path=/share/android/camera state=directory owner=jay group=users mode=700

- name: create /share/android/pictures
  file: path=/share/android/pictures state=directory owner=jay group=users mode=700


## Remove default directories
- name: remove ~/Desktop
  file: path=/home/jay/Desktop state=absent

- name: remove ~/Documents
  file: path=/home/jay/Documents state=absent

- name: remove ~/Downloads
  file: path=/home/jay/Downloads state=absent

- name: remove ~/Music
  file: path=/home/jay/Music state=absent

- name: remove ~/Pictures
  file: path=/home/jay/Pictures state=absent

- name: remove ~/Public
  file: path=/home/jay/Public state=absent

- name: remove ~/Templates
  file: path=/home/jay/Templates state=absent

- name: remove ~/Videos
  file: path=/home/jay/Videos state=absent
