- name: enable and start daemon (ntpd)
  service: name=ntpd enabled=yes state=started
  when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro']

- name: enable and start daemon (ntp)
  service: name=ntp enabled=yes state=started
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
