- name: install kvm virtualization host
  hosts: kvm_hosts
  become: True
  tasks:

  ## Arch Linux
  - name: install kvm packages (arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - bridge-utils
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager


  ## Fedora
  - name: install kvm packages (fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - bridge-utils
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager


  ## Debian and Ubuntu
  - name: install kvm packages (debian-based)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - bridge-utils
      - libvirt-bin
      - qemu-kvm
      - qemu-system
      - virt-manager
      - virt-top
      - virtinst


  ## Manage kvm group
  - name: create kvm group
    group: name=kvm system=yes state=present

  - name: add user to kvm group
    user: name=jay groups=kvm append=yes


  ## Create required directories
  - name: create /vm_store directory
    file: path=/vm_store state=directory owner=root group=kvm mode=770

  - name: create /vm_store/kvm directory
    file: path=/vm_store/kvm state=directory owner=root group=kvm mode=770

  - name: create /vm_store/iso_images directory
    file: path=/vm_store/iso_images state=directory owner=root group=kvm mode=770

  - name: create /etc/libvirt directory
    file: path=/etc/libvirt state=directory owner=root group=root mode=755

  - name: create storage directory
    file: path=/etc/libvirt/storage state=directory owner=root group=root mode=755


  ## Copy configuration files
  - name: copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: copy qemu.conf
    copy: src=../files/kvm_host/qemu.conf dest=/etc/libvirt/qemu.conf owner=root group=root mode=600
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution in ['Linuxmint', 'Ubuntu']

  - name: copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution in ['Linuxmint', 'Ubuntu']

  - name: copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution in ['Linuxmint', 'Ubuntu']

  - name: copy qemu.conf
    copy: src=../files/kvm_host/qemu.conf dest=/etc/libvirt/qemu.conf owner=root group=root mode=600
    notify: restart libvirt-bin
    when: ansible_distribution in ['Linuxmint', 'Ubuntu']


  ## libvirt daemon
  - name: enable libvirtd
    service: name=libvirtd enabled=yes state=started
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']
    
  - name: enable libvirt-bin
    service: name=libvirt-bin enabled=yes state=started
    when: ansible_distribution in ['Linuxmint', 'Ubuntu']


  handlers:
  - name: restart libvirtd
    service: name=libvirtd state=restarted
    
  - name: restart libvirt-bin
    service: name=libvirt-bin state=restarted
