- include: packages_arch.yml
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']

- include: packages_debian_ubuntu.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- include: packages_fedora.yml
  when: ansible_distribution in ['Fedora']

- include: dconf_nautilus.yml
- include: dconf_keybindings.yml
