- name: install gnome (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - file-roller
    - gedit
    - gnome-control-center
    - gnome-music
    - gnome-power-manager
    - gnome-shell
    - gnome-shell-extensions
    - gnome-system-monitor
    - gnome-terminal
    - gnome-tweak-tool
    - nautilus
