- name: install gnome
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - file-roller
    - gedit
    - gnome-control-center
    - gnome-music
    - gnome-power-manager
    - gnome-shell
    - gnome-shell-extensions
    - gnome-system-monitor
    - gnome-terminal
    - gnome-tweak-tool
    - nautilus
    - ttf-liberation
