- name: create jay group
  group: name=jay
         state=present
         gid=1000

- name: create user jay
  user: name=jay
        state=present
        password="{{ jay_passwd }}"
        group="jay"
        uid=1000
        shell=/bin/bash
  notify: change_ownership_jay
