- name: create jay group
  group: name=jay state=present gid=1000

- name: create user jay
  user: name=jay
        state=present
        password="$6$.oovVtp9LRVPLaDP$tCNQA8BkZ72YQgNkKnRVsKJcOGYKJlnQvfMrfgFjpZI0LP.0Dr68F3Yajkc3ClrSSl/ZPgb1M8WcYOCpH5f8f/"
        group="jay"
        uid=1000
        shell=/bin/bash
  notify: change_ownership_jay
