- name: create jay group
  group: name=jay state=present gid=1000

- name: create user jay
  user: name=jay state=present password="$6$qt9.2TKgIhhQR$NeZenG1pNdyO8Y19uCq1IDrArv0TVC7JVTvQmjiuIYBzab1DD/e5K7aq87D3z5sgpIZQeDD8b5LPlMlfw3Vcg." group="jay" uid=1000 shell=/bin/bash
  notify: change_ownership_jay

- name: create .config directory
  file: path=/home/jay/.config state=directory owner=jay group=jay mode=700

- name: copy user-dirs.dirs
  copy: src=jay_user-dirs.dirs dest=/home/jay/.config/user-dirs.dirs owner=jay group=jay mode=600

- name: create .ssh directory
  file: path=/home/jay/.ssh state=directory owner=jay group=jay mode=700

- name: copy ssh config file
  copy: src=jay_ssh_config dest=/home/jay/.ssh/config owner=jay group=jay mode=600

- name: copy ssh authorized_keys file
  copy: src=jay_authorized_keys dest=/home/jay/.ssh/authorized_keys owner=jay group=jay mode=600
