- name: copy .bashrc (root)
  copy: src=root/bashrc dest=/root/.bashrc owner=root group=root mode=600

- name: copy .bash_profile (root)
  copy: src=root/bash_profile dest=/root/.bash_profile owner=root group=root mode=600

- name: copy .tmux.conf (root)
  copy: src=root/tmux.conf dest=/root/.tmux.conf owner=root group=root mode=600

- name: copy .vimrc (root)
  copy: src=root/vimrc dest=/root/.vimrc owner=root group=root mode=600

- name: create .vim directory (root)
  file: path=/root/.vim state=directory owner=root group=root mode=700

- name: create .vim/colors directory (root)
  file: path=/root/.vim/colors state=directory owner=root group=root mode=700

- name: copy bubblegum-256-dark.vim (root)
  copy: src=shared/bubblegum-256-dark.vim dest=/root/.vim/colors/bubblegum-256-dark.vim owner=root group=root mode=600

- name: copy darktango.vim (root)
  copy: src=shared/darktango.vim dest=/root/.vim/colors/darktrango.vim owner=root group=root mode=600

- name: copy jellybeans.vim (root)
  copy: src=shared/jellybeans.vim dest=/root/.vim/colors/jellybeans.vim owner=root group=root mode=600

- name: copy xoria256.vim (root)
  copy: src=shared/xoria256.vim dest=/root/.vim/colors/xoria256.vim owner=root group=root mode=600

- name: copy zenburn.vim (root)
  copy: src=shared/zenburn.vim dest=/root/.vim/colors/zenburn.vim owner=root group=root mode=600
