- name: install openbox (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - clipit
    - compton
    - fonts-cantarell
    - gksu
    - gmrun
    - gnome-themes-standard
    - gsimplecal
    - lxappearance
    - mousepad
    - nitrogen
    - obconf
    - obmenu
    - openbox
    - pcmanfm
    - scrot
    - tint2
    - volumeicon-alsa
    - xarchiver
    - xscreensaver
