- name: install openbox (arch)
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - acpid
    - cantarell-fonts
    - clipit
    # - compton # Not currently available, only in AUR
    - gksu
    - gmrun
    - gnome-themes-standard
    - gsimplecal
    - lxappearance
    - mousepad
    - nitrogen
    - obconf
    - oblogout
    - obmenu
    - pcmanfm
    - scrot
    - tint2
    - ttf-liberation
    - volumeicon
    - xarchiver
    - xscreensaver


- name: copy oblogout.conf (arch)
  copy: src=oblogout.conf dest=/etc/oblogout.conf owner=root group=root mode=644
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
