- name: install openbox
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - cantarell-fonts
    - clipit
    # - compton # Not currently available, only in AUR
    - gksu
    - gmrun
    - gnome-themes-standard
    - gsimplecal
    - lxappearance
    - mousepad
    - nitrogen
    - obconf
    - oblogout
    - obmenu
    - pcmanfm
    - scrot
    - tint2
    - ttf-liberation
    - volumeicon
    - xarchiver
    - xscreensaver
