- name: install openbox
  dnf: name={{item}} state=latest
  when: ansible_distribution == 'Fedora'
  with_items:
    - abattis-cantarell-fonts
    - clipit
    #- compton # Not available
    - gmrun
    - gnome-themes-standard
    #- gsimplecal # Package not available
    - lxappearance
    - mousepad
    - nitrogen
    - obconf
    - obmenu
    - pcmanfm
    - scrot
    - tint2
    - volumeicon
    - xarchiver
    - xbacklight
    - xscreensaver
