- name: set up light display manager
  hosts: dm-lightdm
  become: True
  tasks:

  - name: install lightdm (debian-based)
    apt: name=lightdm
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

  - name: install lightdm (arch)
    pacman: name=lightdm
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: install acpid (arch)
    pacman: name=acpid
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: install lightdm-gtk-greeter (arch)
    pacman: name=lightdm-gtk-greeter
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: enable gdm (arch)
    service: name=gdm enabled=no
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: enable gdm3 (debian-based)
    service: name=gdm3 enabled=no
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

  - name: enable lightdm
    service: name=lightdm enabled=yes
