- name: set up gnome display manager
  hosts: dm-gdm
  become: True
  tasks:

  - name: install gdm (arch)
    pacman: name=gdm
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: install gdm (debian-based)
    apt: name=gdm3
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

  - name: disable lightdm
    service: name=lightdm enabled=no

  - name: enable gdm (arch)
    service: name=gdm enabled=yes
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - name: enable gdm3 (debian-based)
    service: name=gdm3 enabled=yes
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
