- name: Install KVM virtualization host
  hosts: kvm_hosts
  sudo: True
  tasks:

  ## Arch Linux
  - name: Install KVM packages (Arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - bridge-utils
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager


  ## Fedora
  - name: Install KVM packages (Fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - bridge-utils
      - dnsmasq
      - ebtables
      - libvirt
      - qemu
      - virt-manager


  ## Debian and Ubuntu
  - name: Install KVM packages (Debian & Ubuntu)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Ubuntu']
    with_items:
      - bridge-utils
      - libvirt-bin
      - qemu-kvm
      - qemu-system
      - virt-manager
      - virt-top
      - virtinst


  ## Create required directories
  - name: Create /vm_store directory
    file: path=/vm_store state=directory owner=root group=kvm mode=770

  - name: Create /vm_store/kvm directory
    file: path=/vm_store/kvm state=directory owner=root group=kvm mode=770

  - name: Create /vm_store/iso_images directory
    file: path=/vm_store/iso_images state=directory owner=root group=kvm mode=770

  - name: Create /etc/libvirt directory
    file: path=/etc/libvirt state=directory owner=root group=root mode=755

  - name: Create storage directory
    file: path=/etc/libvirt/storage state=directory owner=root group=root mode=755


  ## Copy configuration files
  - name: Copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'

  - name: Copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'
    
  - name: Copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'


  ## libvirt daemon
  - name: Enable libvirtd
    service: name=libvirtd enabled=yes state=started
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']
    
  - name: Enable libvirt-bin
    service: name=libvirt-bin enabled=yes state=started
    when: ansible_distribution == 'Ubuntu'


  handlers:
  - name: restart libvirt
    service: name=libvirtd state=restarted
    
  - name: restart libvirt-bin
    service: name=libvirt-bin state=restarted
