- name: Install KVM virtualization host
  hosts: kvm_hosts
  sudo: True
  tasks:

  ## Arch Linux
  - pacman: name=bridge-utils
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=dnsmasq
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=ebtables
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=libvirt
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=qemu
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=virt-manager
    when: ansible_distribution in ['Archlinux', 'Manjaro']


  ## Fedora
  - dnf: name=bridge-utils
    when: ansible_distribution == 'Fedora'

  - dnf: name=dnsmasq
    when: ansible_distribution == 'Fedora'

  - dnf: name=ebtables
    when: ansible_distribution == 'Fedora'

  - dnf: name=libvirt
    when: ansible_distribution == 'Fedora'

  - dnf: name=qemu
    when: ansible_distribution == 'Fedora'

  - dnf: name=virt-manager
    when: ansible_distribution == 'Fedora'


  ## Debian and Ubuntu
  - apt: name=bridge-utils
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=libvirt-bin
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=qemu-kvm
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=qemu-system
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=virt-manager
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=virt-top
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=virtinst
    when: ansible_distribution in ['Debian', 'Ubuntu']


  ## Create required directories
  - name: Create libvirt directory
    file: path=/etc/libvirt state=directory owner=root group=root mode=755

  - name: Create storage directory
    file: path=/etc/libvirt/storage state=directory owner=root group=root mode=755


  ## Copy configuration files
  - name: Copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirtd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy libvirtd.conf
    copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'

  - name: Copy default.xml
    copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'
    
  - name: Copy iso.xml
    copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirt-bin
    when: ansible_distribution == 'Ubuntu'

  ## libvirt daemon
  - name: Enable libvirtd
    service: name=libvirtd enabled=yes state=started
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']
    
  - name: Enable libvirt-bin
    service: name=libvirt-bin enabled=yes state=started
    when: ansible_distribution == 'Ubuntu'


  handlers:
  - name: restart libvirt
    service: name=libvirtd state=restarted
    
  - name: restart libvirt-bin
    service: name=libvirt-bin state=restarted
