- name: Install KVM virtualization host
  hosts: kvm_hosts
  sudo: True
  tasks:

  ## Arch Linux
  - pacman: name=bridge-utils
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=dnsmasq
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=ebtables
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=libvirt
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=qemu
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=virt-manager
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'


  ## Fedora
  - dnf: name=bridge-utils
    when: ansible_distribution == 'Fedora'

  - dnf: name=dnsmasq
    when: ansible_distribution == 'Fedora'

  - dnf: name=ebtables
    when: ansible_distribution == 'Fedora'

  - dnf: name=libvirt
    when: ansible_distribution == 'Fedora'

  - dnf: name=qemu
    when: ansible_distribution == 'Fedora'

  - dnf: name=virt-manager
    when: ansible_distribution == 'Fedora'


  ## Debian and Ubuntu
  - apt: name=bridge-utils
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=libvirt-bin
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=qemu-kvm
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=qemu-system
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=virt-manager
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=virt-top
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=virtinst
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


  ## Create required directories
  - name: Create libvirt directory
    file: path=/etc/libvirt state=directory owner=root group=root mode=755

  - name: Create storage directory
    file: path=/etc/libvirt/storage state=directory owner=root group=root mode=755


  ## Copy configuration files
  - copy: src=../files/kvm_host/libvirtd.conf dest=/etc/libvirt/libvirtd.conf owner=root group=root mode=644
    notify: restart libvirt

  - copy: src=../files/kvm_host/default.xml dest=/etc/libvirt/storage/default.xml owner=root group=root mode=644
    notify: restart libvirt

  - copy: src=../files/kvm_host/iso.xml dest=/etc/libvirt/storage/iso.xml owner=root group=root mode=644
    notify: restart libvirt


  ## libvirt daemon
  - name: Enable libvirt
    service: name=libvirtd enabled=yes state=started
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Debian' or ansible_distribution == 'Fedora' or ansible_distribution == 'Manjarolinux'
    service: name=libvirt-bin enabled=yes state=started
    when: ansible_distribution == 'Ubuntu'


  handlers:
  - name: restart libvirt
    service: name=libvirtd state=restarted
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Fedora' or ansible_distribution == 'Debian' or ansible_distribution == 'Manjarolinux'
    service: name=libvirt-bin state=restarted
    when: ansible_distribution == 'Ubuntu'
