- name: Configure OpenSSH server on port 65001
  hosts: openssh_p65001
  sudo: True
  tasks:

  ## Install packages
  - pacman: name=openssh
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - dnf: name=openssh
    when: ansible_distribution == 'Fedora'

  - yum: name=openssh-server
    when: ansible_distribution == 'CentOS'

  - apt: name=openssh-server
    when: ansible_distribution in ['Debian', 'Ubuntu']


  ## Copy sshd_config
  - name: Copy sshd_config
    copy: src=../files/openssh/sshd_config_p65001 dest=/etc/ssh/sshd_config owner=root group=root mode=644
    notify: Restart sshd
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro']


  ## Copy sshd_config
  - name: Copy sshd_config
    copy: src=../files/openssh/sshd_config_p65001 dest=/etc/ssh/sshd_config owner=root group=root mode=644
    notify: Restart ssh
    when: ansible_distribution in ['Debian', 'Ubuntu']


  ## Copy /etc/issue.net
  - name: Copy issue.net
    copy: src=../files/openssh/issue.net dest=/etc/issue.net owner=root group=root mode=644


  ## Install /etc/motd update script
  - name: Copy motd script
    copy: src=../files/openssh/system_stats.sh dest=/usr/local/bin/system_stats.sh owner=root group=root mode=755


  ## Ensure cron is available
  - pacman: name=cronie
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - apt: name=cron
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - dnf: name=cronie
    when: ansible_distribution == 'Fedora'


  ## Set up the crontab for system_stats.sh script
  - cron: name="update_stats" job="/usr/local/bin/system_stats.sh > /dev/null"


  ## Set up the daemon
  - service: name=sshd enabled=yes state=started
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro']

  - service: name=ssh enabled=yes state=started
    when: ansible_distribution in ['Debian', 'Ubuntu']


  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted

  - name: Restart sshd
    service: name=sshd state=restarted
