- name: Configure OpenSSH server on port 22
  hosts: openssh_p22
  sudo: True
  tasks:

  ## Install packages
  - pacman: name=openssh
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - dnf: name=openssh
    when: ansible_distribution == 'Fedora'

  - yum: name=openssh-server
    when: ansible_distribution == 'CentOS'

  - apt: name=openssh-server
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


  ## Copy sshd_config
  - name: Copy sshd_config
    copy: src=../files/openssh/sshd_config_p22 dest=/etc/ssh/sshd_config owner=root group=root mode=644
    notify: restart sshd


  ## Set up the daemon
  - service: name=sshd enabled=yes state=started
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'Manjarolinux'

  - service: name=ssh enabled=yes state=started
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  handlers:
  - name: restart sshd
    service: name=sshd state=restarted
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'Manjarolinux'
    service: name=ssh state=restarted
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
