- name: Install base packages on hosts
  hosts: servers:workstations
  sudo: True
  tasks:

  ## Archlinux and Manjaro
  - pacman: name=colordiff
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=curl
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=git
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=htop
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=iotop
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=linux-lts
    when: ansible_distribution == 'Archlinux'

  - pacman: name=linux-lts-headers
    when: ansible_distribution == 'Archlinux'

  - pacman: name=lm_sensors
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=lynx
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=mosh
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=ncdu
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=rsync
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=screen
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=sshfs
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=sudo
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=the_silver_searcher
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=tmux
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=vim-python3
    when: ansible_distribution in ['Archlinux', 'Manjaro']


  ## Fedora
  - dnf: name=colordiff
    when: ansible_distribution == 'Fedora'

  - dnf: name=curl
    when: ansible_distribution == 'Fedora'

  - dnf: name=git
    when: ansible_distribution == 'Fedora'

  - dnf: name=htop
    when: ansible_distribution == 'Fedora'

  - dnf: name=iotop
    when: ansible_distribution == 'Fedora'

  - dnf: name=lm_sensors
    when: ansible_distribution == 'Fedora'

  - dnf: name=lynx
    when: ansible_distribution == 'Fedora'

  - dnf: name=mailx
    when: ansible_distribution == 'Fedora'

  - dnf: name=mosh
    when: ansible_distribution == 'Fedora'

  - dnf: name=ncdu
    when: ansible_distribution == 'Fedora'

  - dnf: name=rsync
    when: ansible_distribution == 'Fedora'

  - dnf: name=screen
    when: ansible_distribution == 'Fedora'

  - dnf: name=sshfs
    when: ansible_distribution == 'Fedora'

  - dnf: name=sudo
    when: ansible_distribution == 'Fedora'

  - dnf: name=the_silver_searcher
    when: ansible_distribution == 'Fedora'

  - dnf: name=tmux
    when: ansible_distribution == 'Fedora'

  - dnf: name=vim-enhanced
    when: ansible_distribution == 'Fedora'


  ## CentOS
  - yum: name=colordiff
    when: ansible_distribution == 'CentOS'

  - yum: name=curl
    when: ansible_distribution == 'CentOS'

  - yum: name=fuse-sshfs
    when: ansible_distribution == 'CentOS'

  - yum: name=git
    when: ansible_distribution == 'CentOS'

  - yum: name=htop
    when: ansible_distribution == 'CentOS'

  - yum: name=iotop
    when: ansible_distribution == 'CentOS'

  - yum: name=lm_sensors
    when: ansible_distribution == 'CentOS'

  - yum: name=lynx
    when: ansible_distribution == 'CentOS'

  - yum: name=mosh
    when: ansible_distribution == 'CentOS'

  - yum: name=ncdu
    when: ansible_distribution == 'CentOS'

  - yum: name=rsync
    when: ansible_distribution == 'CentOS'

  - yum: name=screen
    when: ansible_distribution == 'CentOS'

  - yum: name=sudo
    when: ansible_distribution == 'CentOS'

  - yum: name=tmux
    when: ansible_distribution == 'CentOS'

  - yum: name=vim-enhanced
    when: ansible_distribution == 'CentOS'


   ## Debian and Ubuntu
  - apt: name=colordiff
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=curl
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=exim4 state=absent
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=exim4-base state=absent
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=exim4-config state=absent
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=git
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=heirloom-mailx
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=htop
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=iotop
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=lm-sensors
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=lynx
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=mosh
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=ncdu
    when: ansible_distribution in ['Debian', 'Ubuntu']

  #- apt: name=silversearcher-ag update_cache=yes # Not currently available on some versions of raspbian
  #  when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=rsync
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=screen
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=sshfs
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=sudo
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=tmux
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=vim-nox
    when: ansible_distribution in ['Debian', 'Ubuntu']
