- name: Install development tools on hosts
  hosts: servers:workstations
  sudo: True
  tasks:

  ## Archlinux
  - name: Install dev packages (Arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - flake8
      - python-pyflakes
      - python2-flake8
      - python2-pip
      - python2-pyflakes
      - python-virtualenv
      - python2-virtualenv
      - ruby
      - tig


  ## Fedora
  - name: Install dev packages (Fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - pyflakes
      - python-flake8
      - python3-flake8
      - python-pep8
      - python3-pep8
      - python3-pyflakes
      - python-pip
      - python-virtualenv
      - ruby
      - tig


  ## Debian and Ubuntu
  - name: Install dev packages (Debian-based)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - pyflakes
      - python-dev
      - python-flake8
      - python3-flake8
      - python-pip
      - python-virtualenv
      - ruby
      - ruby-dev
      - rake
      - tig
