- name: Install game packages
  hosts: workstations-games
  sudo: True
  tasks:

  ## Archlinux
  - name: Install games on Archlinux hosts
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - chromium-bsu
      - frozen-bubble
      - lib32-gcc-libs
      - lib32-libpulse
      - mednafen
      - neverball
      - sdlmame
      - supertux
      - supertuxkart
      - wesnoth


  ## Fedora
  - name: Install games on Fedora hosts
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - alsa-lib.i686
      - chromium-bsu
      - frozen-bubble
      - glibc.i686
      - mame
      - mednafen
      - mesa-dri-drivers.i686
      - neverball
      - pulseaudio-libs.i686
      - supertux
      - supertuxkart
      - wesnoth


  ## Debian and Ubuntu
  - name: Install games on Debian-based hosts
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - chromium-bsu
      - frozen-bubble
      - libasound2-data
      - libasound2-plugins:i386
      - libc6:i386
      - mame
      - mednafen
      - neverball
      - supertux
      - supertuxkart
      - wesnoth


## Install mame.ini
  - name: Create mame directory (Debian-based)
    file: path=/etc/mame state=directory owner=root group=root mode=755
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
   
  - name: Copy mame.ini (Debian-based)
    copy: src=../files/packages_games/mame.ini dest=/etc/mame/mame.ini owner=root group=users mode=644
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

  - name: Create mame directory (Arch)
    file: path=/home/jay/.mame state=directory owner=jay group=jay mode=700
    when: ansible_distribution in ['Archlinux', 'Manjaro']
   
  - name: Copy mame.ini (Arch)
    copy: src=../files/packages_games/mame.ini dest=/home/jay/.mame/mame.ini owner=jay group=jay mode=600
    when: ansible_distribution in ['Archlinux', 'Manjaro']

