- name: Install development tools on hosts
  hosts: servers:workstations
  sudo: True
  tasks:

  ## Archlinux
  - name: Install dev packages (Arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - python2-pip
      - tig


  ## Fedora
  - name: Install dev packages (Fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - python-pip
      - tig


  ## Debian and Ubuntu
  - name: Install dev packages (Debian-based)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - python-dev
      - python-pip
      - tig
