- name: Install packages on workstation hosts
  hosts: workstations
  sudo: True
  tasks:

  ## Arch Linux
  - name: Install workstation packages (Arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - asunder
      - banshee
      - brasero
      - cmus
      - conky
      - cryptsetup
      - dmenu
      - easytag
      - exfat-utils
      - filezilla
      - freerdp
      - galculator
      - geany
      - geany-plugins
      - gimp
      - gparted
      - gtk-engine-aurora
      - gtk-engine-murrine
      - gtk-recordmydesktop
      - guake
      - keepassx
      - libreoffice-still
      - mpv
      - pavucontrol
      - perl
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode # To do: Unable to install the proper package, rxvt-unicode-pixbuf, via yaourt
      - shutter
      - smbclient
      - terminator
      - terminus-font
      - transmission-gtk
      - vlc
      - vorbis-tools
      - xsel


  ## Debian
  - name: Install workstation packages (Debian and Ubuntu)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Ubuntu']
    with_items:
      - aptitude
      - asunder
      - banshee
      - brasero
      - cmus
      - conky
      - cryptsetup
      - easytag
      - exfat-utils
      - filezilla
      - freerdp-x11
      - galculator
      - geany
      - geany-plugins
      - gimp
      - gparted
      - gtk-recordmydesktop
      - gtk2-engines-aurora
      - gtk2-engines-murrine
      - guake
      - keepassx
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-impress
      - mpv
      - pavucontrol
      - perl
      - pyrenamer
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode-256color
      - shutter
      - smbclient
      - suckless-tools
      - synaptic
      - terminator
      - transmission-gtk
      - vlc
      - vorbis-tools
      - xfonts-terminus
      - xsel


  ## Fedora
  - name: Install workstation packages (Fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - asunder
      - banshee
      - brasero
      #- cmus # Currently not available in Fedora, check this later
      - conky
      - easytag
      - exfat-utils
      - filezilla
      - freerdp
      - galculator
      - geany
      - gimp
      - gparted
      - gtk2-engines
      - gtk-recordmydesktop
      - guake
      - keepassx
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-writer
      #- mpv # Package not found
      - pavucontrol
      - perl
      - pyrenamer
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode-256color
      - shutter
      - terminator
      - terminus-fonts
      - transmission-gtk
      - vlc
      - vorbis-tools
      - xsel
