- name: Install base packages on hosts
  hosts: servers:workstations
  sudo: True
  tasks:


  ## Archlinux and Manjaro
  - name: Install Archlinux base packages
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - colordiff
      - curl
      - git
      - htop
      - iotop
      - linux-lts
      - linux-lts-headers
      - lm_sensors
      - lynx
      - mosh
      - ncdu
      - rsync
      - screen
      - sshfs
      - the_silver_searcher
      - tmux
      - vim-python3


  ## Fedora packages
  - name: Install Fedora base packages
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - colordiff
      - curl
      - git
      - htop
      - iotop
      - lm_sensors
      - lynx
      - mailx
      - mosh
      - ncdu
      - rsync
      - screen
      - sshfs
      - the_silver_searcher
      - tmux
      - vim-enhanced


    ## CentOS packages
  - name: Install CentOS base packages
    yum: name={{item}} state=installed
    when: ansible_distribution == 'CentOS'
    with_items:
      - colordiff
      - curl
      - fuse-sshfs
      - git
      - htop
      - iotop
      - lm_sensors
      - lynx
      - mosh
      - ncdu
      - rsync
      - screen
      - tmux
      - vim-enhanced


   ## Debian and Ubuntu
  - name: Install Debian base packages
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Ubuntu']
    with_items:
      - colordiff
      - curl
      - git
      - heirloom-mailx
      - htop
      - iotop
      - lm-sensors
      - lynx
      - mosh
      - ncdu
      - rsync
      - screen
      # silversearcher-ag # Not currently available on some versions of raspbian
      - sshfs
      - tmux
      - vim-nox


  - name: Remove unneeded Debian packages
    apt: name={{ item }} state=absent
    when: ansible_distribution in ['Debian', 'Ubuntu']
    with_items:
      - exim4
      - exim4-base
      - exim4-config

