- name: Install development tools on hosts
  hosts: servers:workstations
  sudo: True
  tasks:

  ## Archlinux
  - pacman: name=python2-pip
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - pacman: name=tig
    when: ansible_distribution in ['Archlinux', 'Manjaro']


  ## Fedora
  - dnf: name=python-pip
    when: ansible_distribution == 'Fedora'

  - dnf: name=tig
    when: ansible_distribution == 'Fedora'


  ## Debian and Ubuntu
  - apt: name=python-dev
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=python-pip
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - apt: name=tig
    when: ansible_distribution in ['Debian', 'Ubuntu']
