- name: configure raspberry pi hosts
  hosts: raspberry-pi
  become: True
  tasks:

  ## Raspbian packages to install
  - name: install packages on raspbian hosts
    apt: name={{item}} state=installed
    with_items:
      - dhcpcd5

  ## Ensure dhcpcd5 is running
  - name: start and enable dhcpcd
    service: name=dhcpcd enabled=yes state=started

  ## Copy network_check script
  - name: copy network_check script
    copy: src=../files/pi/network_check dest=/usr/local/bin/network_check owner=root group=root mode=755

  ## Ensure cron is available
  - name: ensure cron is installed
    apt: name=cron
    when: ansible_distribution in ['Debian', 'Ubuntu']

  ## Set up the crontab
  - name: add network_check cron job
    cron: name="network_check" minute="*/2" hour="*" day="*" job="/usr/local/bin/network_check > /dev/null"
