- name: Configure Raspberry Pi hosts
  hosts: raspberry-pi
  sudo: True
  tasks:

  ## Raspbian packages to install
  - name: Install packages on Raspbian hosts
    apt: name={{item}} state=installed
    with_items:
      - dhcpcd5

  ## Ensure dhcpcd5 is running
  - service: name=dhcpcd enabled=yes state=started

  ## Copy network_check script
  - name: Copy network_check script (Pi)
    copy: src=../files/scripts_pi/network_check dest=/usr/local/bin/network_check owner=root group=root mode=755

  ## Ensure cron is available
  - name: Ensure cron is installed
    apt: name=cron
    when: ansible_distribution in ['Debian', 'Ubuntu']

  ## Set up the crontab
  - cron: name="network_check" minute="*/2" hour="*" day="*" job="/usr/local/bin/network_check > /dev/null"
