- name: Install scripts on servers
  hosts: servers
  sudo: True
  tasks:


  ## Copy script files
  - copy: src=../files/scripts_server/email-params dest=/usr/local/bin/.email-params owner=root group=root mode=755
  - copy: src=../files/scripts_server/email_etc_backup dest=/usr/local/bin/email_etc_backup owner=root group=root mode=755
  - copy: src=../files/scripts_server/email_package_list dest=/usr/local/bin/email_package_list owner=root group=root mode=755
  - copy: src=../files/scripts_server/process_check.py dest=/usr/local/bin/process_check.py owner=root group=root mode=755
  - copy: src=../files/scripts_server/update dest=/usr/local/bin/update owner=root group=root mode=755
  - copy: src=../files/scripts_server/weekly_update dest=/usr/local/bin/weekly_update owner=root group=root mode=755


  ## Ensure cron is available
  - pacman: name=cronie
    when: ansible_distribution in ['Archlinux', 'Manjaro']

  - apt: name=cron
    when: ansible_distribution in ['Debian', 'Ubuntu']

  - dnf: name=cronie
    when: ansible_distribution == 'Fedora'


  ## Set up the crontab
  - cron: name="weekly_update" minute="0" hour="1" weekday="5" job="/usr/local/bin/weekly_update > /dev/null"
  - cron: name="email_etc_backup" minute="0" hour="2" weekday="5" job="/usr/local/bin/email_etc_backup > /dev/null"
  - cron: name="email_package_list" minute="0" hour="3" weekday="5" job="/usr/local/bin/email_package_list > /dev/null"
