- name: Install and configure Syncthing client
  hosts: workstations
  sudo: True

  vars:
    syncthing_version: 0.12.3
    syncthing_url: https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-linux-amd64-v{{syncthing_version}}.tar.gz
    app_dir: /home/jay/bin/apps
    syncthing_config: /home/jay/.config/syncthing/config.xml


  tasks:

  - name: Create syncthing directory
    file: path={{app_dir}}/syncthing state=directory owner=jay group=jay mode=700
    register: client

  ## Copy syncthing startup script
  - copy: src=../files/syncthing/systemd_syncthing dest=/etc/systemd/system/syncthing.service owner=root group=root mode=644

  - name: download syncthing
    get_url: url="{{syncthing_url}}" dest=/tmp/syncthing_{{syncthing_version}}.tar.gz
    when: client.changed

  - name: extract syncthing
    unarchive: src=/tmp/syncthing_{{syncthing_version}}.tar.gz dest={{app_dir}} copy=no
    when: client.changed


  ## Set up the daemon
  - service: name=syncthing enabled=yes state=started


  - name: wait for config.xml to be generated
    wait_for: path={{syncthing_config}}


  - name: config.xml | webinterface address
    lineinfile: dest={{syncthing_config}}
                regexp="<address>[^<]+</address>"
                line="        <address>0.0.0.0:8324</address>"
    notify: restart syncthing


  - name: config.xml | upnpEnabled
    lineinfile: dest={{syncthing_config}}
                regexp="<upnpEnabled>[^<]+</upnpEnabled>"
                line="        <upnpEnabled>false</upnpEnabled>"
    notify: restart syncthing


  handlers:
    - name: restart syncthing
      service: name=syncthing state=restarted

    - name: correct ownership
      command: chown jay:jay -R {{syncthing_home}}
