- name: Install and configure Syncthing client
  hosts: workstations
  sudo: True

  vars:
    syncthing_version: 0.12.4
    syncthing_url: https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-linux-amd64-v{{syncthing_version}}.tar.gz
    app_dir: /home/jay/bin
    syncthing_config: /home/jay/.config/syncthing/config.xml


  tasks:

  - name: Copy syncthing startup script (systemd)
    copy: src=../files/users_jay/systemd_syncthing dest=/etc/systemd/system/syncthing.service owner=root group=root mode=644
    when: ansible_distribution in ['Archlinux', 'CentOS', 'Debian', 'Fedora', 'Manjaro']

  - name: Copy syncthing startup script (sysv)
    copy: src=../files/users_jay/sysv_syncthing dest=/etc/init.d/syncthing owner=root group=root mode=755
    when: ansible_distribution in ['Linuxmint']

  - name: Create syncthing directory
    file: path={{app_dir}}/syncthing state=directory owner=jay group=jay recurse=true
    register: client

  - name: download syncthing
    get_url: url="{{syncthing_url}}" dest=/tmp/syncthing_{{syncthing_version}}.tar.gz
    when: client.changed

  - name: extract syncthing
    unarchive: src=/tmp/syncthing_{{syncthing_version}}.tar.gz dest=/tmp copy=no
    when: client.changed

  - name: install syncthing
    shell: cp /tmp/syncthing-*/syncthing {{app_dir}}/syncthing
    when: client.changed

  - name: correct ownership
    command: chown jay:jay -R {{app_dir}}
    when: client.changed

  - name: correct permissions
    command: chmod g-rwx,o-rwx -R {{app_dir}}
    when: client.changed

  - name: cleanup
    command: rm -rf /tmp/syncthing*
    when: client.changed

  ## Set up the daemon
  - service: name=syncthing enabled=yes state=started


  - name: wait for config.xml to be generated
    wait_for: path={{syncthing_config}}


  - name: config.xml | webinterface address
    lineinfile: dest={{syncthing_config}}
                regexp="<address>[^<]+</address>"
                line="        <address>0.0.0.0:8324</address>"
    notify: restart syncthing


  - name: config.xml | upnpEnabled
    lineinfile: dest={{syncthing_config}}
                regexp="<upnpEnabled>[^<]+</upnpEnabled>"
                line="        <upnpEnabled>false</upnpEnabled>"
    notify: restart syncthing


  handlers:
    - name: restart syncthing
      service: name=syncthing state=restarted
