- name: install openbox packages on hosts
  hosts: workstations-openbox
  become: True
  tasks:


  ## Archlinux and Manjaro
  - name: install openbox (arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - acpid
      - cantarell-fonts
      - clipit
      # - compton # Not currently available, only in AUR
      - gksu
      - gmrun
      - gnome-themes-standard
      - gsimplecal
      - lxappearance
      - mousepad
      - nitrogen
      - obconf
      - oblogout
      - obmenu
      - pcmanfm
      - scrot
      - tint2
      - volumeicon
      - xarchiver
      - xscreensaver


  - name: copy oblogout.conf (arch)
    copy: src=../files/openbox/oblogout.conf dest=/etc/oblogout.conf owner=root group=root mode=644
    when: ansible_distribution in ['Archlinux', 'Manjaro']


   ## Debian and Ubuntu
  - name: install openbox (debian-based)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - acpid
      - clipit
      - compton
      - fonts-cantarell
      - gksu
      - gmrun
      - gnome-themes-standard
      - gsimplecal
      - lxappearance
      - mousepad
      - nitrogen
      - obconf
      - obmenu
      - openbox
      - pcmanfm
      - scrot
      - tint2
      - volumeicon-alsa
      - xarchiver
      - xscreensaver


  ## Fedora
  - name: install openbox (fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - abattis-cantarell-fonts
      - acpid
      - clipit
      #- compton # Not available
      - gmrun
      - gnome-themes-standard
      #- gsimplecal # Package not available
      - lxappearance
      - mousepad
      - nitrogen
      - obconf
      - obmenu
      - pcmanfm
      - scrot
      - tint2
      - volumeicon
      - xarchiver
      - xscreensaver


  # Copy config files
  - name: copy oblogout.conf (Arch)
    copy: src=../files/openbox/oblogout.conf dest=/etc/oblogout.conf owner=root group=root mode=644
    when: ansible_distribution in ['Archlinux', 'Manjaro']
