- name: Set up workstation hosts
  hosts: workstations
  become: True
  tasks:

  ## Arch Linux
  - name: Install workstation packages (Arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro']
    with_items:
      - asunder
      - banshee
      - brasero
      - cmus
      - conky
      - cryptsetup
      - dialog
      - dmenu
      - easytag
      - exfat-utils
      - filezilla
      - freerdp
      - galculator
      - geany
      - geany-plugins
      - gimp
      - gnome-keyring
      - gparted
      - gtk-engine-aurora
      - gtk-engine-murrine
      - gtk-recordmydesktop
      - guake
      - hunspell-en
      - hyphen-en
      - keepassx
      - libreoffice-still
      - mpv
      - network-manager-applet
      - networkmanager
      - networkmanager-openvpn
      - networkmanager-pptp
      - networkmanager-vpnc
      - pavucontrol
      - perl
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode # To do: Unable to install the proper package, rxvt-unicode-pixbuf, via yaourt
      - shutter
      - smbclient
      - terminator
      - terminus-font
      - transmission-gtk
      - vlc
      - vorbis-tools
      - wireless_tools
      - wpa_actiond
      - wpa_supplicant
      - xorg-xbacklight
      - xsel


  ## Debian
  - name: Install workstation packages (Debian and Ubuntu)
    apt: name={{item}} state=installed
    when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
    with_items:
      - aptitude
      - asunder
      - banshee
      - brasero
      - cmus
      - conky
      - cryptsetup
      - easytag
      - exfat-utils
      - filezilla
      - firmware-iwlwifi
      - freerdp-x11
      - galculator
      - geany
      - geany-plugins
      - gimp
      - gnome-keyring
      - gparted
      - gtk-recordmydesktop
      - gtk2-engines-aurora
      - gtk2-engines-murrine
      - guake
      - hunspell-en-us
      - hyphen-en-us
      - keepassx
      - libreoffice-calc
      - libreoffice-gnome
      - libreoffice-impress
      - libreoffice-writer
      - mpv
      - network-manager
      - network-manager-openvpn
      - network-manager-openvpn-gnome
      - network-manager-pptp
      - network-manager-vpnc
      - pavucontrol
      - perl
      - pyrenamer
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode-256color
      - shutter
      - smbclient
      - suckless-tools
      - synaptic
      - terminator
      - transmission-gtk
      - vlc
      - vorbis-tools
      - xbacklight
      - xfonts-terminus
      - xsel


  ## Fedora
  - name: Install workstation packages (Fedora)
    dnf: name={{item}} state=installed
    when: ansible_distribution == 'Fedora'
    with_items:
      - asunder
      - banshee
      - brasero
      #- cmus # Currently not available in Fedora, check this later
      - conky
      - dmenu
      - easytag
      - exfat-utils
      - filezilla
      - freerdp
      - galculator
      - geany
      - gimp
      - gnome-keyring
      - gparted
      - gstreamer-plugins-bad
      - gstreamer-plugins-good
      - gstreamer-plugins-ugly
      - gstreamer1-plugins-ugly # To do: Which gstreamer packages are actually necessary?
      - gtk2-engines
      - gtk-recordmydesktop
      - guake
      - keepassx
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-writer
      #- mpv # Package not found
      - pavucontrol
      - perl
      - pyrenamer
      - quassel-client
      - rdesktop
      - remmina
      - roxterm
      - rxvt-unicode-256color
      - shutter
      - terminator
      - terminus-fonts
      - transmission-gtk
      - vlc
      - vorbis-tools
      - xbacklight
      - xsel


# Configure Network Manager

  - name: Enable devices for network manager (Debian)
    lineinfile: dest=/etc/NetworkManager/NetworkManager.conf regexp=^managed= line=managed=true


  # Enable service
  - name: Enable Network Manager service
    service: name=NetworkManager enabled=yes


  ## Set up directories
  - file: path=/home/jay/bin state=directory owner=jay group=users mode=700
  - file: path=/home/jay/desktop state=directory owner=jay group=users mode=700
  - file: path=/home/jay/documents state=directory owner=jay group=users mode=700
  - file: path=/home/jay/downloads state=directory owner=jay group=users mode=700
  - file: path=/home/jay/games state=directory owner=jay group=users mode=700
  - file: path=/home/jay/music state=directory owner=jay group=users mode=700
  - file: path=/home/jay/pictures state=directory owner=jay group=users mode=700
  - file: path=/home/jay/projects state=directory owner=jay group=users mode=700
  - file: path=/home/jay/templates state=directory owner=jay group=users mode=700
  - file: path=/home/jay/videos state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/archive state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/backup state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/downloads state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/private state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/public state=directory owner=jay group=users mode=700
  - file: path=/mnt/pluto/videos state=directory owner=jay group=users mode=700
  - file: path=/share state=directory owner=jay group=users mode=700
  - file: path=/share/android state=directory owner=jay group=users mode=700
  - file: path=/share/android/camera state=directory owner=jay group=users mode=700
  - file: path=/share/android/pictures state=directory owner=jay group=users mode=700


  ## Remove default directories
  - file: path=/home/jay/Desktop state=absent
  - file: path=/home/jay/Documents state=absent
  - file: path=/home/jay/Downloads state=absent
  - file: path=/home/jay/Music state=absent
  - file: path=/home/jay/Pictures state=absent
  - file: path=/home/jay/Public state=absent
  - file: path=/home/jay/Templates state=absent
  - file: path=/home/jay/Videos state=absent

