- name: apt-update
  apt: update_cache=yes
  when: ansible_distribution in ['Debian', 'Ubuntu']
  changed_when: False

- include: packages.yml
- include: cron.yml
- include: ntp.yml
- include: sudoers.yml
- include: openssh.yml
