- name: install or update ntp (centos)
  yum: name=ntp state=latest
  when: ansible_distribution == 'CentOS'
  notify: restart_ntpd

- name: copy ntp.conf
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=755
  when: ansible_distribution in ['CentOS']
  notify: restart_ntpd

- name: enable and start daemon (ntpd)
  service: name=ntpd enabled=yes state=started
  when: ansible_distribution in ['CentOS']
