- name: install or update openssh
  dnf: name=openssh state=latest
  notify: restart_sshd
  when: ansible_distribution == 'Fedora'

- name: enable sshd
  service: name=sshd enabled=yes state=started
  when: ansible_distribution in ['CentOS', 'Fedora']

- name: copy sshd_config
  template: src=sshd_config_fedora.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=644
  notify: restart_sshd
  when: ansible_distribution in ['Fedora']
