- name: install or update openssh (arch)
  pacman: name=openssh state=latest
  notify: restart_sshd
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']

- name: install or update openssh (fedora)
  dnf: name=openssh state=latest
  notify: restart_sshd
  when: ansible_distribution == 'Fedora'

- name: install or update openssh (centos)
  yum: name=openssh-server state=latest
  notify: restart_sshd
  when: ansible_distribution == 'CentOS'

- name: install or update openssh (debian-based)
  apt: name=openssh-server state=latest
  notify: restart_ssh
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: enable sshd
  service: name=sshd enabled=yes state=started
  when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro Linux']

- name: enable ssh
  service: name=ssh enabled=yes state=started
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: copy sshd_config (triggers sshd)
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=644
  notify: restart_sshd
  when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro Linux']

- name: copy sshd_config (triggers ssh)
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config owner=root group=root mode=644
  notify: restart_ssh
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: copy issue.net
  copy: src=openssh_issue.net dest=/etc/issue.net owner=root group=root mode=644

- name: copy motd script
  copy: src=motd.sh dest=/etc/profile.d/motd.sh owner=root group=root mode=755

- name: copy motd file
  copy: src=motd dest=/etc/motd owner=root group=root mode=755
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: disable standard-motd
  lineinfile: dest=/etc/pam.d/login
              regexp="session    optional   pam_motd.so"
              line="#session    optional   pam_motd.so"
