- name: install base packages
  pacman: name={{item}} state=installed
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
  with_items:
    - base-devel
    - bind-tools
    - binutils
    - colordiff
    - cronie
    - curl
    - fakeroot
    - flake8
    - flex
    - gawk
    - git
    - grep
    - htop
    - iotop
    - linux-lts
    - linux-lts-headers
    - lm_sensors
    - lynx
    - mc
    - mosh
    - ncdu
    - python-pyflakes
    - python-virtualenv
    - python2-flake8
    - python2-pip
    - python2-pyflakes
    - python2-virtualenv
    - ranger
    - rsync
    - ruby
    - screen
    - sshfs
    - the_silver_searcher
    - tig
    - tmux
    - vim
    - wget
