- name: install base packages (centos)
  yum: name={{item}} state=installed
  when: ansible_distribution == 'CentOS'
  with_items:
    - colordiff
    - cronie
    - curl
    - fuse-sshfs
    - git
    - htop
    - iotop
    - lm_sensors
    - lynx
    - mosh
    - ncdu
    - rsync
    - screen
    - tmux
    - vim-enhanced
    - wget

- name: install base packages (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  with_items:
    - aptitude
    - colordiff
    - cron
    - curl
    - dnsutils
    - git
    - heirloom-mailx
    - htop
    - iotop
    - lm-sensors
    - lynx
    - mosh
    - ncdu
    - pyflakes
    - python-dev
    - python-flake8
    - python-pip
    - python-virtualenv
    - python3-flake8
    - rake
    - rsync
    - ruby
    - ruby-dev
    - screen
    - silversearcher-ag
    - sshfs
    - tig
    - tmux
    - vim-nox
    - wget

- name: remove unneeded debian packages
  apt: name={{item}} state=absent
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  with_items:
    - exim4
    - exim4-base
    - exim4-config
    - nano

- name: install base packages (fedora)
  dnf: name={{item}} state=installed
  when: ansible_distribution == 'Fedora'
  with_items:
    - colordiff
    - cronie
    - curl
    - git
    - htop
    - iotop
    - lm_sensors
    - lynx
    - mailx
    - mosh
    - ncdu
    - pyflakes
    - python-flake8
    - python-pep8
    - python-pip
    - python-virtualenv
    - python3-flake8
    - python3-pep8
    - python3-pyflakes
    - rsync
    - ruby
    - screen
    - sshfs
    - the_silver_searcher
    - tig
    - tmux
    - vim-enhanced
    - wget
