- name: install base packages
  dnf: name={{item}} state=latest
  when: ansible_distribution == 'Fedora'
  with_items:
    - colordiff
    - cronie
    - curl
    - git
    - htop
    - iotop
    - lm_sensors
    - lnav
    - lynx
    - mailx
    - mc
    - mosh
    - ncdu
    - pyflakes
    - python-flake8
    - python-pep8
    - python-pip
    - python-virtualenv
    - python3-flake8
    - python3-pep8
    - python3-pyflakes
    - ranger
    - rsync
    - ruby
    - screen
    - sshfs
    - the_silver_searcher
    - tig
    - tmux
    - vim-enhanced
    - wget
