- name: install base packages
  apt: name={{item}} state=latest
  when: ansible_distribution in ['Debian']
  with_items:
    - aptitude
    - colordiff
    - cron
    - curl
    - dnsutils
    - git
    - heirloom-mailx
    - htop
    - iotop
    - lm-sensors
    - lnav
    - lynx
    - mosh
    - ncdu
    - pyflakes
    - python-dev
    - python-flake8
    - python-pip
    - python-virtualenv
    - python3-flake8
    - rake
    - rsync
    - ruby
    - ruby-dev
    - screen
    - silversearcher-ag
    - sshfs
    - tig
    - vim-nox
    - wget

# Splitting tmux into two sections, Raspbian isn't compatible with backports.
- name: install tmux (debian)
  apt: name=tmux state=latest default_release=jessie-backports
  when: not ansible_architecture|match('arm')

- name: install tmux (raspbian)
  apt: name=tmux state=latest
  when: ansible_architecture|match('arm')

- name: remove unneeded debian packages
  apt: name={{item}} state=absent purge=yes
  when: ansible_distribution in ['Debian']
  with_items:
    - exim4
    - exim4-base
    - exim4-config
    - nano
