- name: install epel
  yum: name={{item}} state=latest
  when: ansible_distribution == 'CentOS'
  with_items:
    - epel-release

- name: install base packages
  yum: name={{item}} state=latest
  when: ansible_distribution == 'CentOS'
  with_items:
    - colordiff
    - cronie
    - curl
    - fuse-sshfs
    - git
    - htop
    - iotop
    - lm_sensors
    - lnav
    - lynx
    - mosh
    - ncdu
    - rsync
    - screen
    - tmux
    - vim-enhanced
    - wget
