- name: install sources.list
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=644
  when: not ansible_architecture|match('arm')

- name: enable backports
  copy: src=jessie_backports.list dest=/etc/apt/sources.list.d/backports.list owner=root group=root mode=644
  when: not ansible_architecture|match('arm')

- name: enable 32-bit packages
  copy: src=arch dest=/var/lib/dpkg/arch owner=root group=root mode=644
  when: not ansible_architecture|match('arm')

- name: apt-update
  apt: update_cache=yes
  when: ansible_distribution in ['Debian']
  changed_when: False
