- name: install rpm fusion free
  dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm state=present
  when: ansible_distribution == 'Fedora'

- name: install rpm fusion non-free
  dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm state=present
  when: ansible_distribution == 'Fedora'
