- name: enable 32-bit packages
  copy: src=arch dest=/var/lib/dpkg/arch owner=root group=root mode=644
  when: ansible_distribution in ['Ubuntu']

- name: add syncthing repository key
  apt_key: url=https://syncthing.net/release-key.txt state=present
  when: ansible_distribution in ['Ubuntu']

- name: add syncthing repository
  #apt_repository: repo='deb http://apt.syncthing.net/ syncthing release' state=present filename='syncthing'
  copy: src=syncthing.list dest=/etc/apt/sources.list.d/syncthing.list owner=root group=root mode=644
  when: ansible_distribution in ['Ubuntu']

- name: apt-update
  apt: update_cache=yes
  when: ansible_distribution in ['Ubuntu']
  changed_when: False
