- name: copy .email-params
  copy: src=email-params dest=/usr/local/bin/.email-params owner=root group=root mode=755

- name: copy email_etc_backup script
  copy: src=script_email_etc_backup dest=/usr/local/bin/email_etc_backup owner=root group=root mode=755

- name: copy email_package_list script
  copy: src=script_email_package_list dest=/usr/local/bin/email_package_list owner=root group=root mode=755

- name: copy process_check.py script
  copy: src=script_process_check.py dest=/usr/local/bin/process_check.py owner=root group=root mode=755
