- name: create admins group
  group: name=admins system=yes state=present gid=901

- name: add jay to admins group
  user: name=jay groups=admins append=yes

- name: make sure suders includes the appropriate directory
  lineinfile: "dest=/etc/sudoers
               state=present
               line='#includedir /etc/sudoers.d'
               validate='/usr/sbin/visudo -cf %s'"

- name: copy sudoers_ansible
  copy: src=sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

- name: copy sudoers_admins
  copy: src=sudoers_admins dest=/etc/sudoers.d/admins owner=root group=root mode=0440

# The admins group is used to control sudo, so remove the %sudo lines.
- lineinfile: dest=/etc/sudoers line="# Allow members of group sudo to execute any command" state=absent validate="visudo -cf %s"
- lineinfile: dest=/etc/sudoers state=absent regexp="^%sudo" validate="visudo -cf %s"


# This needs to be removed later, after it runs on all machines.
- name: copy sudoers_custom
  file: path=/etc/sudoers.d/sudoers_custom state=absent

- lineinfile: dest=/etc/sudoers line="%admins ALL=(ALL:ALL) ALL" state=absent validate="visudo -cf %s"
- lineinfile: 'dest=/etc/sudoers line="ansible ALL=(ALL) NOPASSWD: ALL" state=absent validate="visudo -cf %s"'
