- name: create admins group
  group: name=admins system=yes state=present gid=901

- name: add jay to admins group
  user: name=jay groups=admins append=yes

- name: make sure admins group is allowed in sudoers
  lineinfile: "dest=/etc/sudoers
               state=present
               line='#includedir /etc/sudoers.d'
               validate='/usr/sbin/visudo -cf %s'"

- name: copy sudoers_ansible
  copy: src=sudoers_ansible dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

- name: copy sudoers_admins
  copy: src=sudoers_admins dest=/etc/sudoers.d/admins owner=root group=root mode=0440

# This needs to be removed later.
- name: copy sudoers_custom
  file: path=/etc/sudoers.d/sudoers_custom owner=root state=absent
