- name: install nrpe package (centos)
  yum: name=nrpe state=latest
  when: ansible_distribution == 'CentOS'

- name: install nagios-plugins package (centos)
  yum: name=nagios-plugins state=latest
  when: ansible_distribution == 'CentOS'

- name: install nagios-plugins-disk package (centos)
  yum: name=nagios-plugins-disk state=latest
  when: ansible_distribution == 'CentOS'

- name: install nagios-plugins-load package (centos)
  yum: name=nagios-plugins-load state=latest
  when: ansible_distribution == 'CentOS'

- name: install nagios-plugins-swap package (centos)
  yum: name=nagios-plugins-swap state=latest
  when: ansible_distribution == 'CentOS'
