- name: Video - Virtualbox
  hosts: arch-workstations-vbox-video
  become: True
  tasks:

  - name: install packages for vbox guest video (arch)
    pacman: name={{item}} state=installed
    when: ansible_distribution in ['Archlinux', 'Manjaro Linux']
    with_items:
      - lib32-libgl
      - lib32-mesa
      - mesa
      - mesa-libgl
      - virtualbox-guest-utils
      - xf86-input-libinput
      - xorg-server
      - xorg-server-utils
      - xorg-xinit

  # Configure driver
  - name: Copy virtualbox.conf to /etc/modules-load.d
    copy: src=../files/arch_video_vbox/virtualbox.conf dest=/etc/modules-load.d/virtualbox.conf owner=root group=root mode=644
