- name: Configure Nagios client
  hosts: servers
  sudo: True
  tasks:

  ## Install packages
  - dnf: name=nagios-plugins
    when: ansible_distribution == 'Fedora'

  - dnf: name=nrpe
    when: ansible_distribution == 'Fedora'

  - pacman: name=nrpe
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - pacman: name=monitoring-plugins
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - yum: name=nrpe
    when: ansible_distribution == 'CentOS'

  - yum: name=nagios-plugins
    when: ansible_distribution == 'CentOS'

  - apt: name=nagios-nrpe-server
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - apt: name=nagios-nrpe-plugin
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  ## Copy nrpe.cfg
  - copy: src=files/nagios_client/nrpe_arch.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'
  - copy: src=files/nagios_client/nrpe_fedora.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
    when: ansible_distribution == 'Fedora'
  - copy: src=files/nagios_client/nrpe_centos.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
    when: ansible_distribution == 'CentOS'
  - copy: src=files/nagios_client/nrpe_debian.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  ## Copy plugins
  - copy: src=files/nagios_client/check_ram dest=/usr/lib64/nagios/plugins/check_ram owner=root group=root mode=644
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'
  - copy: src=files/nagios_client/check_ram dest=/usr/lib/nagios/plugins/check_ram owner=root group=root mode=644
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


  ## Set up the daemon
  - service: name=nrpe enabled=yes state=started
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora' or ansible_distribution == 'Manjarolinux'

  - service: name=nagios-nrpe-server enabled=yes state=started
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
