- name: Configure NTP client
  hosts: servers
  sudo: True
  tasks:

  ## Install packages
  - pacman: name=ntp
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - apt: name=ntp
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - yum: name=ntp
    when: ansible_distribution == 'CentOS'


  ## Copy ntp.conf
  - name: Copy ntp.conf
    copy: src=files/ntp/ntp.conf dest=/etc/ntp.conf owner=root group=root mode=755
    notify: restart ntp


  ## Set up the daemon
  - service: name=ntpd enabled=yes state=started
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - service: name=ntpd enabled=yes state=started
    when: ansible_distribution == 'CentOS'

  - service: name=ntp enabled=yes state=started
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


  handlers:
  - name: restart ntp
    service: name=ntp state=restarted
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    service: name=ntpd state=restarted
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'CentOS' or ansible_distribution == 'Manjarolinux'
