- name: Install scripts on servers
  hosts: servers
  sudo: True
  tasks:

  ## Copy script files
  - copy: src=files/server_scripts/email-params dest=/usr/local/bin/.email-params owner=root group=root mode=755
  - copy: src=files/server_scripts/email_etc_backup dest=/usr/local/bin/email_etc_backup owner=root group=root mode=755
  - copy: src=files/server_scripts/email_package_list dest=/usr/local/bin/email_package_list owner=root group=root mode=755
  - copy: src=files/server_scripts/process_check.py dest=/usr/local/bin/process_check.py owner=root group=root mode=755
  - copy: src=files/server_scripts/update dest=/usr/local/bin/update owner=root group=root mode=755
  - copy: src=files/server_scripts/weekly_update dest=/usr/local/bin/weekly_update owner=root group=root mode=755
  - copy: src=files/server_scripts/sendemail dest=/usr/local/bin/sendemail owner=root group=root mode=755


  ## Ensure cron is available
  - pacman: name=cronie
    when: ansible_distribution == 'Archlinux' or ansible_distribution == 'Manjarolinux'

  - apt: name=cron
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - dnf: name=cronie
    when: ansible_distribution == 'Fedora'


  ## Set up the crontab
  - cron: name="weekly_update" minute="0" hour="1" day="5" job="/usr/local/bin/weekly_update > /dev/null"
  - cron: name="email_etc_backup" minute="0" hour="2" day="5" job="/usr/local/bin/email_etc_backup > /dev/null"
  - cron: name="email_package_list" minute="0" hour="3" day="5" job="/usr/local/bin/email_package_list > /dev/null"
