- name: Set up user jay
  hosts: workstations:servers
  sudo: True
  tasks:


  ## Create user group
  - name: create jay group
    group: name=jay state=present gid=1000


  ## Create user and add to groups
  - name: create user jay
    user: name=jay state=present password="$1$Xwd4P1Od$gSL2PgGDSgEAIcFSvQcoS0" group="jay" uid=1000 shell=/bin/bash groups=admins append=yes


  ## Create .ssh directory
  - name: Create .ssh directory
    file: path=/home/jay/.ssh state=directory owner=jay group=jay mode=700


  ## Populate .ssh directory
  - copy: src=files/users_jay/config dest=/home/jay/.ssh/config owner=jay group=jay mode=600
  - copy: src=files/users_jay/authorized_keys dest=/home/jay/.ssh/authorized_keys owner=jay group=jay mode=600
