- name: install nagios-plugins package (fedora)
  dnf: name=nagios-plugins
  when: ansible_distribution == 'Fedora'

- name: install nrpe package (fedora)
  dnf: name=nrpe
  when: ansible_distribution == 'Fedora'

- name: install nrpe package (arch)
  pacman: name=nrpe
  when: ansible_distribution in ['Archlinux', 'Manjaro']

- name: install monitoring-plugins package (arch)
  pacman: name=monitoring-plugins
  when: ansible_distribution in ['Archlinux', 'Manjaro']

- name: install nrpe package (centos)
  yum: name=nrpe
  when: ansible_distribution == 'CentOS'

- name: install nagios-plugins package (centos)
  yum: name=nagios-plugins
  when: ansible_distribution == 'CentOS'

- name: install nagios-nrpe-server package (debian-based)
  apt: name=nagios-nrpe-server
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: install nagios-nrpe-plugin package (debian-based)
  apt: name=nagios-nrpe-plugin
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: copy nrpe.cfg (arch)
  copy: src=nrpe_arch.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
  when: ansible_distribution in ['Archlinux', 'Manjaro']
  notify: restart_nrpe

- name: copy nrpe.cfg (fedora)
  copy: src=nrpe_fedora.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
  when: ansible_distribution == 'Fedora'
  notify: restart_nrpe

- name: copy nrpe.cfg (centos)
  copy: src=nrpe_centos.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
  when: ansible_distribution == 'CentOS'
  notify: restart_nrpe

- name: copy nrpe.cfg (debian-based)
  copy: src=nrpe_debian.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
  when: ansible_distribution in ['Debian', 'Ubuntu']
  notify: restart_nagios-nrpe-server

- name: copy check_ram plugin (centos, fedora)
  copy: src=nrpe_check_ram dest=/usr/lib64/nagios/plugins/check_ram owner=root group=root mode=644
  when: ansible_distribution in ['CentOS', 'Fedora']

- name: copy check_ram plugin (debian-based)
  copy: src=nrpe_check_ram dest=/usr/lib/nagios/plugins/check_ram owner=root group=root mode=644
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: enable nrpe daemon (arch, centos, fedora)
  service: name=nrpe enabled=yes state=started
  when: ansible_distribution in ['Archlinux', 'CentOS', 'Fedora', 'Manjaro']

- name: enable nagios-nrpe-server daemon (debian-based)
  service: name=nagios-nrpe-server enabled=yes state=started
  when: ansible_distribution in ['Debian', 'Ubuntu']
