- name: install nagios-plugins package (fedora)
  dnf: name=nagios-plugins state=latest
  when: ansible_distribution == 'Fedora'

- name: install nrpe package (fedora)
  dnf: name=nrpe state=latest
  when: ansible_distribution == 'Fedora'

- name: copy nrpe.cfg (fedora)
  copy: src=nrpe_fedora.cfg dest=/etc/nagios/nrpe.cfg owner=root group=root mode=644
  when: ansible_distribution == 'Fedora'
  notify: restart_nrpe

- name: copy check_mem plugin (fedora)
  copy: src=check_mem dest=/usr/lib64/nagios/plugins/check_mem owner=root group=root mode=755
  when: ansible_distribution in ['Fedora']

- name: enable nrpe daemon (fedora)
  service: name=nrpe enabled=yes state=started
  when: ansible_distribution in ['Fedora']
