- name: Video - Intel
  hosts: arch-intel-video
  become: True
  tasks:

  - pacman: name=lib32-intel-dri
  - pacman: name=lib32-libgl
  - pacman: name=lib32-mesa
  - pacman: name=mesa
  - pacman: name=mesa-libgl
  - pacman: name=xf86-input-libinput
  - pacman: name=xf86-video-intel
  - pacman: name=xorg-server
  - pacman: name=xorg-xinit
  - pacman: name=xorg-server-utils
