- name: Video - Nvidia
  hosts: arch-workstations-nvidia-video
  become: True
  tasks:

  - pacman: name=lib32-nvidia-libgl
  - pacman: name=mesa
  - pacman: name=nvidia
  - pacman: name=xf86-input-libinput
  - pacman: name=xorg-server
  - pacman: name=xorg-xinit
  - pacman: name=xorg-server-utils
