- name: install kvm packages
  dnf: name={{item}} state=latest
  when: ansible_distribution == 'Fedora'
  with_items:
    - bridge-utils
    - dnsmasq
    - ebtables
    - libvirt
    - qemu
    - virt-manager
