- name: install kvm packages
  apt: name={{item}} state=latest
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - bridge-utils
    - libvirt-bin
    - qemu-kvm
    - qemu-system
    - ssh-askpass
    - virt-manager
    - virt-top
    - virtinst
