- name: install kvm packages (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - bridge-utils
    - libvirt-bin
    - qemu-kvm
    - qemu-system
    - ssh-askpass
    - virt-manager
    - virt-top
    - virtinst
