- name: disable apport in config
  lineinfile: dest=/etc/default/apport
              regexp="enabled="
              line="enabled=0"


- name: stop apport service
  service: name=apport state=stopped
