- name: create ~/bin
  file: path=/home/jay/bin state=directory owner=jay group=users mode=700

- name: create ~/desktop
  file: path=/home/jay/desktop state=directory owner=jay group=users mode=700

- name: create ~/documents
  file: path=/home/jay/documents state=directory owner=jay group=users mode=700

- name: create ~/downloads
  file: path=/home/jay/downloads state=directory owner=jay group=users mode=700

- name: create ~/games
  file: path=/home/jay/games state=directory owner=jay group=users mode=700

- name: create ~/music
  file: path=/home/jay/music state=directory owner=jay group=users mode=700

- name: create ~/pictures
  file: path=/home/jay/pictures state=directory owner=jay group=users mode=700

- name: create ~/projects
  file: path=/home/jay/projects state=directory owner=jay group=users mode=700

- name: create ~/templates
  file: path=/home/jay/templates state=directory owner=jay group=users mode=700

- name: create ~/videos
  file: path=/home/jay/videos state=directory owner=jay group=users mode=700

- name: create /mnt/pluto
  file: path=/mnt/pluto state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/archive
  file: path=/mnt/pluto/archive state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/backup
  file: path=/mnt/pluto/backup state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/downloads
  file: path=/mnt/pluto/downloads state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/private
  file: path=/mnt/pluto/private state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/public
  file: path=/mnt/pluto/public state=directory owner=jay group=users mode=700

- name: create /mnt/pluto/videos
  file: path=/mnt/pluto/videos state=directory owner=jay group=users mode=700

- name: create /share
  file: path=/share state=directory owner=jay group=users mode=700

- name: create /share/android
  file: path=/share/android state=directory owner=jay group=users mode=700

- name: create /share/android/camera
  file: path=/share/android/camera state=directory owner=jay group=users mode=700

- name: create /share/android/pictures
  file: path=/share/android/pictures state=directory owner=jay group=users mode=700

- name: remove ~/Desktop
  file: path=/home/jay/Desktop state=absent

- name: remove ~/Documents
  file: path=/home/jay/Documents state=absent

- name: remove ~/Downloads
  file: path=/home/jay/Downloads state=absent

- name: remove ~/Music
  file: path=/home/jay/Music state=absent

- name: remove ~/Pictures
  file: path=/home/jay/Pictures state=absent

- name: remove ~/Public
  file: path=/home/jay/Public state=absent

- name: remove ~/Templates
  file: path=/home/jay/Templates state=absent

- name: remove ~/Videos
  file: path=/home/jay/Videos state=absent
