- include: packages_arch.yml
  when: ansible_distribution in ['Archlinux', 'Manjaro Linux']

- include: packages_debian.yml
  when: ansible_distribution in ['Debian']

- include: packages_fedora.yml
  when: ansible_distribution in ['Fedora']

- include: packages_ubuntu.yml
  when: ansible_distribution in ['Ubuntu']

- include: network_manager.yml
- include: directories.yml
- include: firefox.yml

- include: syncthing.yml
  when: not ansible_distribution == 'Fedora'

- include: telegram.yml
- include: thunderbird.yml
- include: firewall.yml
