- name: install workstation packages (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - acpid
    - aptitude
    - asunder
    - banshee
    - brasero
    - cmus
    - conky
    - cryptsetup
    - easytag
    - exfat-utils
    - filezilla
    - freerdp-x11
    - galculator
    - geany
    - geany-plugins
    - gimp
    - gnome-keyring
    - gparted
    - gtk-recordmydesktop
    - gtk2-engines-aurora
    - gtk2-engines-murrine
    - guake
    - hunspell-en-us
    - hyphen-en-us
    - keepassx
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-writer
    - mpv
    - network-manager
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-vpnc
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - smbclient
    - suckless-tools
    - synaptic
    - terminator
    - transmission-gtk
    - vlc
    - vorbis-tools
    - xbacklight
    - xfonts-terminus
    - xsel


- name: install iwlwifi driver (debian)
  apt: name=firmware-iwlwifi
  when: ansible_distribution == 'debian'


- name: install workstation packages (fedora)
  dnf: name={{item}} state=installed
  when: ansible_distribution == 'Fedora'
  with_items:
    - acpid
    - asunder
    - banshee
    - brasero
    #- cmus # Currently not available in Fedora, check this later
    - conky
    - dmenu
    - easytag
    - exfat-utils
    - filezilla
    - freerdp
    - galculator
    - geany
    - gimp
    - gnome-keyring
    - gparted
    - gstreamer-plugins-bad
    - gstreamer-plugins-good
    - gstreamer-plugins-ugly
    - gstreamer1-plugins-ugly # To do: Which gstreamer packages are actually necessary?
    - gtk2-engines
    - gtk-recordmydesktop
    - guake
    - keepassx
    - libreoffice-calc
    - libreoffice-draw
    - libreoffice-writer
    #- mpv # Package not found
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - terminator
    - terminus-fonts
    - transmission-gtk
    - vlc
    - vorbis-tools
    - xbacklight
    - xsel
