- name: install workstation packages (ubuntu)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Ubuntu']
  with_items:
    - acpid
    - aptitude
    - asunder
    - banshee
    - brasero
    - cmus
    - conky
    - corebird
    - cryptsetup
    - easytag
    - exfat-utils
    - filezilla
    - freerdp-x11
    - galculator
    - geany
    - geany-plugins
    - gimp
    - gnome-keyring
    - gparted
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gtk-recordmydesktop
    - gtk2-engines-aurora
    - gtk2-engines-murrine
    - guake
    - hunspell-en-us
    - hyphen-en-us
    - keepassx
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-writer
    - mpv
    - network-manager
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-vpnc
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - smbclient
    - suckless-tools
    - synaptic
    - terminator
    - transmission-gtk
    - uget
    - vlc
    - vorbis-tools
    - xbacklight
    - xfonts-terminus
    - xsel

- name: remove unneeded debian packages
  apt: name={{item}} state=absent
  when: ansible_distribution in ['Ubuntu']
  with_items:
    #- deja-dup
    #- duplicity
    - exim4
    - exim4-base
    - exim4-config
    #- gnome-orca
    - nano
    #- onboard
    #- xul-ext-ubufox
    #- xzoom
