- name: install workstation packages (debian-based)
  apt: name={{item}} state=installed
  when: ansible_distribution in ['Debian', 'Ubuntu']
  with_items:
    - acpid
    - aptitude
    - asunder
    - banshee
    - brasero
    - cmus
    - conky
    - cryptsetup
    - easytag
    - exfat-utils
    - filezilla
    - freerdp-x11
    - galculator
    - geany
    - geany-plugins
    - gimp
    - gnome-keyring
    - gparted
    - gstreamer1.0-plugins-ugly
    - gtk-recordmydesktop
    - gtk2-engines-aurora
    - gtk2-engines-murrine
    - guake
    - hunspell-en-us
    - hyphen-en-us
    - keepassx
    - libreoffice-calc
    - libreoffice-gnome
    - libreoffice-impress
    - libreoffice-writer
    - mpv
    - network-manager
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    - network-manager-pptp
    - network-manager-vpnc
    - pavucontrol
    - perl
    - pyrenamer
    - quassel-client
    - rdesktop
    - remmina
    - roxterm
    - rxvt-unicode-256color
    - shutter
    - smbclient
    - suckless-tools
    - synaptic
    - terminator
    - transmission-gtk
    - vlc
    - vorbis-tools
    - xbacklight
    - xfonts-terminus
    - xsel


- name: install iwlwifi driver (debian)
  apt: name=firmware-iwlwifi
  when: ansible_distribution == 'debian'
