- name: install rpm fusion free
  dnf: name=http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-23.noarch.rpm state=present
  when: ansible_distribution == 'Fedora'

- name: install rpm fusion non-free
  dnf: name=http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-23.noarch.rpm state=present
  when: ansible_distribution == 'Fedora'

- name: install sources.list (jessie)
  copy: src=sources.list.jessie dest=/etc/apt/sources.list owner=root group=root mode=644
  when: ansible_distribution_release == 'jessie'
  register: apt

- name: install sources.list (stretch)
  copy: src=sources.list.stretch dest=/etc/apt/sources.list owner=root group=root mode=644
  when: ansible_distribution_release == 'stretch'
  register: apt

- name: enable backports (jessie)
  copy: src=jessie_backports.list dest=/etc/apt/sources.list.d/backports.list owner=root group=root mode=644
  when: ansible_distribution_release == 'jessie'
  register: apt

- name: enable 32-bit packages (debian-based)
  copy: src=arch dest=/var/lib/dpkg/arch owner=root group=root mode=644
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  register: apt

- name: add syncthing repository key (debian-based)
  apt_key: url=https://syncthing.net/release-key.txt state=present
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

- name: add syncthing repository (debian-based)
  #apt_repository: repo='deb http://apt.syncthing.net/ syncthing release' state=present filename='syncthing'
  copy: src=syncthing.list dest=/etc/apt/sources.list.d/syncthing.list owner=root group=root mode=644
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']
  register: apt

- name: apt-update
  apt: update_cache=yes
  when: apt.changed
  changed_when: False
