- name: install syncthing (arch)
  pacman: name=syncthing state=latest
  when: ansible_distribution in ['Archlinux', 'Manjaro']

- name: install syncthing (debian-based)
  apt: name=syncthing state=latest
  when: ansible_distribution in ['Debian', 'Linuxmint', 'Ubuntu']

# - name: enable and start syncthing daemon
#  service: name=syncthing enabled=yes state=started
#  register: syncthing

#- name: wait for config.xml to be generated
#  wait_for: path=/home/jay/.config/syncthing/config.xml

#- name: config.xml | webinterface address
#  lineinfile: dest={{syncthing_config}}
#              regexp="<address>[^<]+</address>"
#              line="        <address>0.0.0.0:8324</address>"
#  notify: restart syncthing
#  when: syncthing.changed

#- name: config.xml | upnpEnabled
#  lineinfile: dest={{syncthing_config}}
#              regexp="<upnpEnabled>[^<]+</upnpEnabled>"
#              line="        <upnpEnabled>false</upnpEnabled>"
#  notify: restart syncthing
