- name: install or upgrade syncthing (debian-based)
  apt: name=syncthing state=latest
  when: ansible_distribution in ['Debian', 'Ubuntu']
  register: syncthing

- name: enable syncthing
  command: systemctl enable syncthing@jay.service
  when: syncthing.changed

- name: restart syncthing
  command: systemctl restart syncthing@jay.service
  when: syncthing.changed
