- name: add syncthing repository key
  apt_key: url=https://syncthing.net/release-key.txt state=present
  when: ansible_distribution in ['Debian', 'Ubuntu']
  register: syncthing_repo

- name: add syncthing repository
  apt_repository: repo='deb http://apt.syncthing.net/ syncthing release' state=present filename='syncthing' mode=644
  when: ansible_distribution in ['Debian', 'Ubuntu']
  register: syncthing_repo

- name: apt-update
  apt: update_cache=yes
  when: syncthing_repo.changed
